// +build cxfx

package cxfx

import (
	"github.com/skycoin/cx/cx/ast"
	"github.com/skycoin/cx/cx/constants"
	"github.com/skycoin/cx/cx/opcodes"
)

func RegisterPackage() {
	// gogl
	opcodes.RegisterFunction("gl.Init", opGlInit, nil, nil)
	opcodes.RegisterFunction("gl.Destroy", opGlDestroy, nil, nil)
	opcodes.RegisterFunction("gl.Strs", opGlStrs, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("gl.Free", opGlFree, opcodes.In(ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("gl.NewTexture", opGlNewTexture, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.NewTextureCube", opGlNewTextureCube, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.NewGIF", opGlNewGIF, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.FreeGIF", opGlFreeGIF, opcodes.In(ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("gl.GIFFrameToTexture", opGlGIFFrameToTexture, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.UploadImageToTexture", opGlUploadImageToTexture, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_BOOL), nil)
	opcodes.RegisterFunction("gl.CxReleaseTexture", opCxReleaseTexture, opcodes.In(ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("gl.CxTextureGetPixel", opCxTextureGetPixel, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32))

	opcodes.RegisterFunction("gl.AppendF32", opGlAppend, opcodes.In(ast.Slice(constants.TYPE_UI8), ast.ConstCxArg_F32), opcodes.Out(ast.Slice(constants.TYPE_UI8)))
	opcodes.RegisterFunction("gl.AppendUI16", opGlAppend, opcodes.In(ast.Slice(constants.TYPE_UI8), ast.ConstCxArg_UI16), opcodes.Out(ast.Slice(constants.TYPE_UI8)))
	opcodes.RegisterFunction("gl.AppendUI32", opGlAppend, opcodes.In(ast.Slice(constants.TYPE_UI8), ast.ConstCxArg_UI32), opcodes.Out(ast.Slice(constants.TYPE_UI8)))

	// gl_0.0
	opcodes.RegisterFunction("gl.MatrixMode", opGlMatrixMode, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.Rotatef", opGlRotatef, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction("gl.Translatef", opGlTranslatef, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction("gl.LoadIdentity", opGlLoadIdentity, nil, nil)
	opcodes.RegisterFunction("gl.PushMatrix", opGlPushMatrix, nil, nil)
	opcodes.RegisterFunction("gl.PopMatrix", opGlPopMatrix, nil, nil)
	opcodes.RegisterFunction("gl.EnableClientState", opGlEnableClientState, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.Color3f", opGlColor3f, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction("gl.Color4f", opGlColor4f, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction("gl.Begin", opGlBegin, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.End", opGlEnd, nil, nil)
	opcodes.RegisterFunction("gl.Normal3f", opGlNormal3f, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction("gl.Vertex2f", opGlVertex2f, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction("gl.Vertex3f", opGlVertex3f, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction("gl.Lightfv", opGlLightfv, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction("gl.Frustum", opGlFrustum, opcodes.In(ast.ConstCxArg_F64, ast.ConstCxArg_F64, ast.ConstCxArg_F64, ast.ConstCxArg_F64, ast.ConstCxArg_F64, ast.ConstCxArg_F64), nil)
	opcodes.RegisterFunction("gl.TexEnvi", opGlTexEnvi, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.Ortho", opGlOrtho, opcodes.In(ast.ConstCxArg_F64, ast.ConstCxArg_F64, ast.ConstCxArg_F64, ast.ConstCxArg_F64, ast.ConstCxArg_F64, ast.ConstCxArg_F64), nil)
	opcodes.RegisterFunction("gl.Scalef", opGlScalef, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction("gl.TexCoord2d", opGlTexCoord2d, opcodes.In(ast.ConstCxArg_F64, ast.ConstCxArg_F64), nil)
	opcodes.RegisterFunction("gl.TexCoord2f", opGlTexCoord2f, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)

	// gl_1_0
	opcodes.RegisterFunction("gl.CullFace", opGlCullFace, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.FrontFace", opGlFrontFace, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.Hint", opGlHint, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.Scissor", opGlScissor, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.TexParameteri", opGlTexParameteri, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.TexImage2D", opGlTexImage2D, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(constants.TYPE_UI32)), nil)
	opcodes.RegisterFunction("gl.Clear", opGlClear, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.ClearColor", opGlClearColor, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction("gl.ClearStencil", opGlClearStencil, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.ClearDepth", opGlClearDepth, opcodes.In(ast.ConstCxArg_F64), nil)
	opcodes.RegisterFunction("gl.StencilMask", opGlStencilMask, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.ColorMask", opGlColorMask, opcodes.In(ast.ConstCxArg_BOOL, ast.ConstCxArg_BOOL, ast.ConstCxArg_BOOL, ast.ConstCxArg_BOOL), nil)
	opcodes.RegisterFunction("gl.DepthMask", opGlDepthMask, opcodes.In(ast.ConstCxArg_BOOL), nil)
	opcodes.RegisterFunction("gl.Disable", opGlDisable, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.Enable", opGlEnable, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.BlendFunc", opGlBlendFunc, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.StencilFunc", opGlStencilFunc, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.StencilOp", opGlStencilOp, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.DepthFunc", opGlDepthFunc, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.GetError", opGlGetError, nil, opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.GetTexLevelParameteriv", opGlGetTexLevelParameteriv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.DepthRange", opGlDepthRange, opcodes.In(ast.ConstCxArg_F64, ast.ConstCxArg_F64), nil)
	opcodes.RegisterFunction("gl.Viewport", opGlViewport, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)

	// gl_1_1
	opcodes.RegisterFunction("gl.DrawArrays", opGlDrawArrays, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.DrawElements", opGlDrawElements, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.BindTexture", opGlBindTexture, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.DeleteTextures", opGlDeleteTextures, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.GenTextures", opGlGenTextures, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))

	// gl_1_3
	opcodes.RegisterFunction("gl.ActiveTexture", opGlActiveTexture, opcodes.In(ast.ConstCxArg_I32), nil)

	// gl_1_4
	opcodes.RegisterFunction("gl.BlendFuncSeparate", opGlBlendFuncSeparate, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)

	// gl_1_5
	opcodes.RegisterFunction("gl.BindBuffer", opGlBindBuffer, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.DeleteBuffers", opGlDeleteBuffers, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.GenBuffers", opGlGenBuffers, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.BufferData", opGlBufferData, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(constants.TYPE_UI8), ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.BufferSubData", opGlBufferSubData, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(constants.TYPE_UI8)), nil)

	//gl_2_0
	opcodes.RegisterFunction("gl.DrawBuffers", opGlDrawBuffers, opcodes.In(ast.ConstCxArg_I32, ast.Slice(constants.TYPE_UI32)), nil)
	opcodes.RegisterFunction("gl.StencilOpSeparate", opGlStencilOpSeparate, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.StencilFuncSeparate", opGlStencilFuncSeparate, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.StencilMaskSeparate", opGlStencilMaskSeparate, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.AttachShader", opGlAttachShader, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.BindAttribLocation", opGlBindAttribLocation, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("gl.CompileShader", opGlCompileShader, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.CreateProgram", opGlCreateProgram, nil, opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.CreateShader", opGlCreateShader, opcodes.In(ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.DeleteProgram", opGlDeleteProgram, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.DeleteShader", opGlDeleteShader, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.DetachShader", opGlDetachShader, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.EnableVertexAttribArray", opGlEnableVertexAttribArray, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.GetAttribLocation", opGlGetAttribLocation, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.GetProgramiv", opGlGetProgramiv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.GetProgramInfoLog", opGlGetProgramInfoLog, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_STR))
	opcodes.RegisterFunction("gl.GetShaderiv", opGlGetShaderiv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.GetShaderInfoLog", opGlGetShaderInfoLog, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_STR))
	opcodes.RegisterFunction("gl.GetUniformLocation", opGlGetUniformLocation, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.LinkProgram", opGlLinkProgram, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.ShaderSource", opGlShaderSource, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("gl.UseProgram", opGlUseProgram, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.Uniform1f", opGlUniform1f, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction("gl.Uniform2f", opGlUniform2f, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction("gl.Uniform3f", opGlUniform3f, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction("gl.Uniform4f", opGlUniform4f, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction("gl.Uniform1i", opGlUniform1i, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.Uniform2i", opGlUniform2i, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.Uniform3i", opGlUniform3i, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.Uniform4i", opGlUniform4i, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.Uniform1fv", opGlUniform1fv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_F32, ast.Slice(constants.TYPE_F32)), nil)
	opcodes.RegisterFunction("gl.Uniform2fv", opGlUniform2fv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_F32, ast.Slice(constants.TYPE_F32)), nil)
	opcodes.RegisterFunction("gl.Uniform3fv", opGlUniform3fv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(constants.TYPE_F32)), nil)
	opcodes.RegisterFunction("gl.Uniform4fv", opGlUniform4fv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(constants.TYPE_F32)), nil)
	opcodes.RegisterFunction("gl.Uniform1iv", opGlUniform1iv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(constants.TYPE_I32)), nil)
	opcodes.RegisterFunction("gl.Uniform2iv", opGlUniform2iv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(constants.TYPE_I32)), nil)
	opcodes.RegisterFunction("gl.Uniform3iv", opGlUniform3iv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(constants.TYPE_I32)), nil)
	opcodes.RegisterFunction("gl.Uniform4iv", opGlUniform4iv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(constants.TYPE_I32)), nil)
	opcodes.RegisterFunction("gl.UniformMatrix2fv", opGlUniformMatrix2fv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_BOOL, ast.Slice(constants.TYPE_F32)), nil)
	opcodes.RegisterFunction("gl.UniformMatrix3fv", opGlUniformMatrix3fv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_BOOL, ast.Slice(constants.TYPE_F32)), nil)
	opcodes.RegisterFunction("gl.UniformMatrix4fv", opGlUniformMatrix4fv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_BOOL, ast.Slice(constants.TYPE_F32)), nil)
	opcodes.RegisterFunction("gl.UniformV4F", opGlUniformV4F, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_UND_TYPE), nil)
	opcodes.RegisterFunction("gl.UniformM44F", opGlUniformM44F, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_BOOL, ast.ConstCxArg_UND_TYPE), nil)
	opcodes.RegisterFunction("gl.UniformM44FV", opGlUniformM44FV, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_BOOL, ast.Slice(constants.TYPE_UNDEFINED)), nil)
	opcodes.RegisterFunction("gl.VertexAttribPointer", opGlVertexAttribPointer, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_BOOL, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.VertexAttribPointerI32", opGlVertexAttribPointerI32, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_BOOL, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)

	// gl_3_0
	opcodes.RegisterFunction("gl.ClearBufferI", opGlClearBufferI, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.ClearBufferUI", opGlClearBufferUI, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_UI32, ast.ConstCxArg_UI32, ast.ConstCxArg_UI32, ast.ConstCxArg_UI32), nil)
	opcodes.RegisterFunction("gl.ClearBufferF", opGlClearBufferF, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction("gl.BindRenderbuffer", opGlBindRenderbuffer, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.DeleteRenderbuffers", opGlDeleteRenderbuffers, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.GenRenderbuffers", opGlGenRenderbuffers, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.RenderbufferStorage", opGlRenderbufferStorage, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.BindFramebuffer", opGlBindFramebuffer, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.DeleteFramebuffers", opGlDeleteFramebuffers, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.GenFramebuffers", opGlGenFramebuffers, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.CheckFramebufferStatus", opGlCheckFramebufferStatus, opcodes.In(ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.FramebufferTexture2D", opGlFramebufferTexture2D, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.FramebufferRenderbuffer", opGlFramebufferRenderbuffer, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.GenerateMipmap", opGlGenerateMipmap, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.BindVertexArray", opGlBindVertexArray, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.BindVertexArrayCore", opGlBindVertexArrayCore, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.DeleteVertexArrays", opGlDeleteVertexArrays, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.DeleteVertexArraysCore", opGlDeleteVertexArraysCore, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gl.GenVertexArrays", opGlGenVertexArrays, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gl.GenVertexArraysCore", opGlGenVertexArraysCore, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))

	// goglfw
	opcodes.RegisterFunction("glfw.Fullscreen", opGlfwFullscreen, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_BOOL, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)

	// glfw
	opcodes.RegisterFunction("glfw.Init", opGlfwInit, nil, nil)
	opcodes.RegisterFunction("glfw.WindowHint", opGlfwWindowHint, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("glfw.CreateWindow", opGlfwCreateWindow, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("glfw.MakeContextCurrent", opGlfwMakeContextCurrent, opcodes.In(ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("glfw.ShouldClose", opGlfwShouldClose, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_BOOL))
	opcodes.RegisterFunction("glfw.SetShouldClose", opGlfwSetShouldClose, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_BOOL), nil)
	opcodes.RegisterFunction("glfw.PollEvents", opGlfwPollEvents, nil, nil)
	opcodes.RegisterFunction("glfw.SwapBuffers", opGlfwSwapBuffers, opcodes.In(ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("glfw.GetFramebufferSize", opGlfwGetFramebufferSize, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction("glfw.GetWindowPos", opGlfwGetWindowPos, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction("glfw.GetWindowSize", opGlfwGetWindowSize, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction("glfw.GetTime", opGlfwGetTime, nil, opcodes.Out(ast.ConstCxArg_F64))
	opcodes.RegisterFunction("glfw.SwapInterval", opGlfwSwapInterval, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("glfw.SetStartCallback", opGlfwSetStartCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("glfw.SetStopCallback", opGlfwSetStopCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("glfw.SetKeyboardCallback", opGlfwSetKeyboardCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("glfw.SetMouseCallback", opGlfwSetMouseCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("glfw.SetFramebufferSizeCallback", opGlfwSetFramebufferSizeCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("glfw.SetWindowPosCallback", opGlfwSetWindowPosCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("glfw.SetWindowSizeCallback", opGlfwSetWindowSizeCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("glfw.SetKeyCallback", opGlfwSetKeyCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)                          // TODO : to deprecate
	opcodes.RegisterFunction("glfw.SetMouseButtonCallback", opGlfwSetMouseButtonCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil) // TODO : to deprecate
	opcodes.RegisterFunction("glfw.SetCursorPosCallback", opGlfwSetCursorPosCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)       // TODO : to deprecate
	opcodes.RegisterFunction("glfw.GetCursorPos", opGlfwGetCursorPos, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_F64, ast.ConstCxArg_F64))
	opcodes.RegisterFunction("glfw.SetInputMode", opGlfwSetInputMode, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("glfw.SetWindowPos", opGlfwSetWindowPos, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("glfw.GetKey", opGlfwGetKey, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("glfw.func_i32_i32", opGlfwFuncI32I32, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("glfw.call_i32_i32", opGlfwCallI32I32, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("glfw.GetWindowContentScale", opGlfwGetWindowContentScale, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction("glfw.GetMonitorContentScale", opGlfwGetMonitorContentScale, nil, opcodes.Out(ast.ConstCxArg_F32, ast.ConstCxArg_F32))

	// gltext
	opcodes.RegisterFunction("gltext.LoadTrueType", opGltextLoadTrueType, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_STR, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gltext.LoadTrueTypeCore", opGltextLoadTrueTypeCore, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_STR, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("gltext.Printf", opGltextPrintf, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction("gltext.Metrics", opGltextMetrics, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gltext.Texture", opGltextTexture, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gltext.NextGlyph", opGltextNextGlyph, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gltext.GlyphBounds", opGltextGlyphBounds, nil, opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gltext.GlyphMetrics", opGltextGlyphMetrics, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction("gltext.GlyphInfo", opGltextGlyphInfo, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32))

	// goal
	opcodes.RegisterFunction("al.LoadWav", opAlLoadWav, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I64, ast.Slice(constants.TYPE_UI8)))

	// openal
	opcodes.RegisterFunction("al.CloseDevice", opAlCloseDevice, nil, nil)
	opcodes.RegisterFunction("al.DeleteBuffers", opAlDeleteBuffers, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("al.DeleteSources", opAlDeleteSources, opcodes.In(ast.Slice(constants.TYPE_I32)), nil)
	opcodes.RegisterFunction("al.DeviceError", opAlDeviceError, nil, opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("al.Error", opAlError, nil, opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("al.Extensions", opAlExtensions, nil, opcodes.Out(ast.ConstCxArg_STR))
	opcodes.RegisterFunction("al.OpenDevice", opAlOpenDevice, nil, nil)
	opcodes.RegisterFunction("al.PauseSources", opAlPauseSources, opcodes.In(ast.Slice(constants.TYPE_I32)), nil)
	opcodes.RegisterFunction("al.PlaySources", opAlPlaySources, opcodes.In(ast.Slice(constants.TYPE_I32)), nil)
	opcodes.RegisterFunction("al.Renderer", opAlRenderer, nil, opcodes.Out(ast.ConstCxArg_STR))
	opcodes.RegisterFunction("al.RewindSources", opAlRewindSources, opcodes.In(ast.Slice(constants.TYPE_I32)), nil)
	opcodes.RegisterFunction("al.StopSources", opAlStopSources, opcodes.In(ast.Slice(constants.TYPE_I32)), nil)
	opcodes.RegisterFunction("al.Vendor", opAlVendor, nil, opcodes.Out(ast.ConstCxArg_STR))
	opcodes.RegisterFunction("al.Version", opAlVersion, nil, opcodes.Out(ast.ConstCxArg_STR))
	opcodes.RegisterFunction("al.GenBuffers", opAlGenBuffers, opcodes.In(ast.ConstCxArg_I32), opcodes.Out(ast.Slice(constants.TYPE_I32)))
	opcodes.RegisterFunction("al.BufferData", opAlBufferData, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_UND_TYPE, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction("al.GenSources", opAlGenSources, opcodes.In(ast.ConstCxArg_I32), opcodes.Out(ast.Slice(constants.TYPE_I32)))
	opcodes.RegisterFunction("al.SourceBuffersProcessed", opAlSourceBuffersProcessed, opcodes.In(ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("al.SourceBuffersQueued", opAlSourceBuffersQueued, opcodes.In(ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("al.SourceQueueBuffers", opAlSourceQueueBuffers, opcodes.In(ast.ConstCxArg_I32, ast.Slice(constants.TYPE_I32)), nil)
	opcodes.RegisterFunction("al.SourceState", opAlSourceState, opcodes.In(ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction("al.SourceUnqueueBuffers", opAlSourceUnqueueBuffers, opcodes.In(ast.ConstCxArg_I32, ast.Slice(constants.TYPE_I32)), nil)
}
