// +build cxfx

package cxfx

import (
	"github.com/skycoin/cx/cx/ast"
	"github.com/skycoin/cx/cx/opcodes"
	"github.com/skycoin/cx/cx/types"
)

func RegisterPackage(prgrm *ast.CXProgram) {
	// gogl
	opcodes.RegisterFunction(prgrm, "gl.Init", opGlInit, nil, nil)
	opcodes.RegisterFunction(prgrm, "gl.Destroy", opGlDestroy, nil, nil)
	opcodes.RegisterFunction(prgrm, "gl.Strs", opGlStrs, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "gl.Free", opGlFree, opcodes.In(ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "gl.NewTexture", opGlNewTexture, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.NewTextureCube", opGlNewTextureCube, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.NewGIF", opGlNewGIF, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.FreeGIF", opGlFreeGIF, opcodes.In(ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "gl.GIFFrameToTexture", opGlGIFFrameToTexture, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.UploadImageToTexture", opGlUploadImageToTexture, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_BOOL), nil)
	opcodes.RegisterFunction(prgrm, "gl.CxReleaseTexture", opCxReleaseTexture, opcodes.In(ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "gl.CxTextureGetPixel", opCxTextureGetPixel, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32))

	opcodes.RegisterFunction(prgrm, "gl.AppendF32", opGlAppend, opcodes.In(ast.Slice(types.UI8), ast.ConstCxArg_F32), opcodes.Out(ast.Slice(types.UI8)))
	opcodes.RegisterFunction(prgrm, "gl.AppendUI16", opGlAppend, opcodes.In(ast.Slice(types.UI8), ast.ConstCxArg_UI16), opcodes.Out(ast.Slice(types.UI8)))
	opcodes.RegisterFunction(prgrm, "gl.AppendUI32", opGlAppend, opcodes.In(ast.Slice(types.UI8), ast.ConstCxArg_UI32), opcodes.Out(ast.Slice(types.UI8)))

	// gl_0.0
	opcodes.RegisterFunction(prgrm, "gl.MatrixMode", opGlMatrixMode, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Rotatef", opGlRotatef, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Translatef", opGlTranslatef, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction(prgrm, "gl.LoadIdentity", opGlLoadIdentity, nil, nil)
	opcodes.RegisterFunction(prgrm, "gl.PushMatrix", opGlPushMatrix, nil, nil)
	opcodes.RegisterFunction(prgrm, "gl.PopMatrix", opGlPopMatrix, nil, nil)
	opcodes.RegisterFunction(prgrm, "gl.EnableClientState", opGlEnableClientState, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Color3f", opGlColor3f, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Color4f", opGlColor4f, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Begin", opGlBegin, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.End", opGlEnd, nil, nil)
	opcodes.RegisterFunction(prgrm, "gl.Normal3f", opGlNormal3f, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Vertex2f", opGlVertex2f, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Vertex3f", opGlVertex3f, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Lightfv", opGlLightfv, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Frustum", opGlFrustum, opcodes.In(ast.ConstCxArg_F64, ast.ConstCxArg_F64, ast.ConstCxArg_F64, ast.ConstCxArg_F64, ast.ConstCxArg_F64, ast.ConstCxArg_F64), nil)
	opcodes.RegisterFunction(prgrm, "gl.TexEnvi", opGlTexEnvi, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Ortho", opGlOrtho, opcodes.In(ast.ConstCxArg_F64, ast.ConstCxArg_F64, ast.ConstCxArg_F64, ast.ConstCxArg_F64, ast.ConstCxArg_F64, ast.ConstCxArg_F64), nil)
	opcodes.RegisterFunction(prgrm, "gl.Scalef", opGlScalef, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction(prgrm, "gl.TexCoord2d", opGlTexCoord2d, opcodes.In(ast.ConstCxArg_F64, ast.ConstCxArg_F64), nil)
	opcodes.RegisterFunction(prgrm, "gl.TexCoord2f", opGlTexCoord2f, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)

	// gl_1_0
	opcodes.RegisterFunction(prgrm, "gl.CullFace", opGlCullFace, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.FrontFace", opGlFrontFace, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Hint", opGlHint, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Scissor", opGlScissor, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.TexParameteri", opGlTexParameteri, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.TexImage2D", opGlTexImage2D, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(types.UI32)), nil)
	opcodes.RegisterFunction(prgrm, "gl.Clear", opGlClear, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.ClearColor", opGlClearColor, opcodes.In(ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction(prgrm, "gl.ClearStencil", opGlClearStencil, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.ClearDepth", opGlClearDepth, opcodes.In(ast.ConstCxArg_F64), nil)
	opcodes.RegisterFunction(prgrm, "gl.StencilMask", opGlStencilMask, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.ColorMask", opGlColorMask, opcodes.In(ast.ConstCxArg_BOOL, ast.ConstCxArg_BOOL, ast.ConstCxArg_BOOL, ast.ConstCxArg_BOOL), nil)
	opcodes.RegisterFunction(prgrm, "gl.DepthMask", opGlDepthMask, opcodes.In(ast.ConstCxArg_BOOL), nil)
	opcodes.RegisterFunction(prgrm, "gl.Disable", opGlDisable, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Enable", opGlEnable, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.BlendFunc", opGlBlendFunc, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.StencilFunc", opGlStencilFunc, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.StencilOp", opGlStencilOp, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.DepthFunc", opGlDepthFunc, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.GetError", opGlGetError, nil, opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.GetTexLevelParameteriv", opGlGetTexLevelParameteriv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.DepthRange", opGlDepthRange, opcodes.In(ast.ConstCxArg_F64, ast.ConstCxArg_F64), nil)
	opcodes.RegisterFunction(prgrm, "gl.Viewport", opGlViewport, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)

	// gl_1_1
	opcodes.RegisterFunction(prgrm, "gl.DrawArrays", opGlDrawArrays, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.DrawElements", opGlDrawElements, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.BindTexture", opGlBindTexture, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.DeleteTextures", opGlDeleteTextures, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.GenTextures", opGlGenTextures, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))

	// gl_1_3
	opcodes.RegisterFunction(prgrm, "gl.ActiveTexture", opGlActiveTexture, opcodes.In(ast.ConstCxArg_I32), nil)

	// gl_1_4
	opcodes.RegisterFunction(prgrm, "gl.BlendFuncSeparate", opGlBlendFuncSeparate, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)

	// gl_1_5
	opcodes.RegisterFunction(prgrm, "gl.BindBuffer", opGlBindBuffer, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.DeleteBuffers", opGlDeleteBuffers, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.GenBuffers", opGlGenBuffers, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.BufferData", opGlBufferData, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(types.UI8), ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.BufferSubData", opGlBufferSubData, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(types.UI8)), nil)

	//gl_2_0
	opcodes.RegisterFunction(prgrm, "gl.DrawBuffers", opGlDrawBuffers, opcodes.In(ast.ConstCxArg_I32, ast.Slice(types.UI32)), nil)
	opcodes.RegisterFunction(prgrm, "gl.StencilOpSeparate", opGlStencilOpSeparate, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.StencilFuncSeparate", opGlStencilFuncSeparate, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.StencilMaskSeparate", opGlStencilMaskSeparate, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.AttachShader", opGlAttachShader, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.BindAttribLocation", opGlBindAttribLocation, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "gl.CompileShader", opGlCompileShader, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.CreateProgram", opGlCreateProgram, nil, opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.CreateShader", opGlCreateShader, opcodes.In(ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.DeleteProgram", opGlDeleteProgram, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.DeleteShader", opGlDeleteShader, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.DetachShader", opGlDetachShader, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.EnableVertexAttribArray", opGlEnableVertexAttribArray, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.GetAttribLocation", opGlGetAttribLocation, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.GetProgramiv", opGlGetProgramiv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.GetProgramInfoLog", opGlGetProgramInfoLog, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_STR))
	opcodes.RegisterFunction(prgrm, "gl.GetShaderiv", opGlGetShaderiv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.GetShaderInfoLog", opGlGetShaderInfoLog, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_STR))
	opcodes.RegisterFunction(prgrm, "gl.GetUniformLocation", opGlGetUniformLocation, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.LinkProgram", opGlLinkProgram, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.ShaderSource", opGlShaderSource, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "gl.UseProgram", opGlUseProgram, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Uniform1f", opGlUniform1f, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Uniform2f", opGlUniform2f, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Uniform3f", opGlUniform3f, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Uniform4f", opGlUniform4f, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Uniform1i", opGlUniform1i, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Uniform2i", opGlUniform2i, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Uniform3i", opGlUniform3i, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Uniform4i", opGlUniform4i, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.Uniform1fv", opGlUniform1fv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_F32, ast.Slice(types.F32)), nil)
	opcodes.RegisterFunction(prgrm, "gl.Uniform2fv", opGlUniform2fv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_F32, ast.Slice(types.F32)), nil)
	opcodes.RegisterFunction(prgrm, "gl.Uniform3fv", opGlUniform3fv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(types.F32)), nil)
	opcodes.RegisterFunction(prgrm, "gl.Uniform4fv", opGlUniform4fv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(types.F32)), nil)
	opcodes.RegisterFunction(prgrm, "gl.Uniform1iv", opGlUniform1iv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(types.I32)), nil)
	opcodes.RegisterFunction(prgrm, "gl.Uniform2iv", opGlUniform2iv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(types.I32)), nil)
	opcodes.RegisterFunction(prgrm, "gl.Uniform3iv", opGlUniform3iv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(types.I32)), nil)
	opcodes.RegisterFunction(prgrm, "gl.Uniform4iv", opGlUniform4iv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.Slice(types.I32)), nil)
	opcodes.RegisterFunction(prgrm, "gl.UniformMatrix2fv", opGlUniformMatrix2fv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_BOOL, ast.Slice(types.F32)), nil)
	opcodes.RegisterFunction(prgrm, "gl.UniformMatrix3fv", opGlUniformMatrix3fv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_BOOL, ast.Slice(types.F32)), nil)
	opcodes.RegisterFunction(prgrm, "gl.UniformMatrix4fv", opGlUniformMatrix4fv, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_BOOL, ast.Slice(types.F32)), nil)
	opcodes.RegisterFunction(prgrm, "gl.UniformV4F", opGlUniformV4F, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_UND_TYPE), nil)
	opcodes.RegisterFunction(prgrm, "gl.UniformM44F", opGlUniformM44F, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_BOOL, ast.ConstCxArg_UND_TYPE), nil)
	opcodes.RegisterFunction(prgrm, "gl.UniformM44FV", opGlUniformM44FV, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_BOOL, ast.Slice(types.UNDEFINED)), nil)
	opcodes.RegisterFunction(prgrm, "gl.VertexAttribPointer", opGlVertexAttribPointer, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_BOOL, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.VertexAttribPointerI32", opGlVertexAttribPointerI32, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_BOOL, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)

	// gl_3_0
	opcodes.RegisterFunction(prgrm, "gl.ClearBufferI", opGlClearBufferI, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.ClearBufferUI", opGlClearBufferUI, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_UI32, ast.ConstCxArg_UI32, ast.ConstCxArg_UI32, ast.ConstCxArg_UI32), nil)
	opcodes.RegisterFunction(prgrm, "gl.ClearBufferF", opGlClearBufferF, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_F32), nil)
	opcodes.RegisterFunction(prgrm, "gl.BindRenderbuffer", opGlBindRenderbuffer, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.DeleteRenderbuffers", opGlDeleteRenderbuffers, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.GenRenderbuffers", opGlGenRenderbuffers, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.RenderbufferStorage", opGlRenderbufferStorage, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.BindFramebuffer", opGlBindFramebuffer, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.DeleteFramebuffers", opGlDeleteFramebuffers, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.GenFramebuffers", opGlGenFramebuffers, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.CheckFramebufferStatus", opGlCheckFramebufferStatus, opcodes.In(ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.FramebufferTexture2D", opGlFramebufferTexture2D, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.FramebufferRenderbuffer", opGlFramebufferRenderbuffer, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.GenerateMipmap", opGlGenerateMipmap, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.BindVertexArray", opGlBindVertexArray, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.BindVertexArrayCore", opGlBindVertexArrayCore, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.DeleteVertexArrays", opGlDeleteVertexArrays, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.DeleteVertexArraysCore", opGlDeleteVertexArraysCore, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gl.GenVertexArrays", opGlGenVertexArrays, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gl.GenVertexArraysCore", opGlGenVertexArraysCore, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))

	// goglfw
	opcodes.RegisterFunction(prgrm, "glfw.Fullscreen", opGlfwFullscreen, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_BOOL, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)

	// glfw
	opcodes.RegisterFunction(prgrm, "glfw.Init", opGlfwInit, nil, nil)
	opcodes.RegisterFunction(prgrm, "glfw.WindowHint", opGlfwWindowHint, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "glfw.CreateWindow", opGlfwCreateWindow, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "glfw.MakeContextCurrent", opGlfwMakeContextCurrent, opcodes.In(ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "glfw.ShouldClose", opGlfwShouldClose, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_BOOL))
	opcodes.RegisterFunction(prgrm, "glfw.SetShouldClose", opGlfwSetShouldClose, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_BOOL), nil)
	opcodes.RegisterFunction(prgrm, "glfw.PollEvents", opGlfwPollEvents, nil, nil)
	opcodes.RegisterFunction(prgrm, "glfw.SwapBuffers", opGlfwSwapBuffers, opcodes.In(ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "glfw.GetFramebufferSize", opGlfwGetFramebufferSize, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "glfw.GetWindowPos", opGlfwGetWindowPos, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "glfw.GetWindowSize", opGlfwGetWindowSize, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "glfw.GetTime", opGlfwGetTime, nil, opcodes.Out(ast.ConstCxArg_F64))
	opcodes.RegisterFunction(prgrm, "glfw.SwapInterval", opGlfwSwapInterval, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "glfw.SetStartCallback", opGlfwSetStartCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "glfw.SetStopCallback", opGlfwSetStopCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "glfw.SetKeyboardCallback", opGlfwSetKeyboardCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "glfw.SetMouseCallback", opGlfwSetMouseCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "glfw.SetFramebufferSizeCallback", opGlfwSetFramebufferSizeCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "glfw.SetWindowPosCallback", opGlfwSetWindowPosCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "glfw.SetWindowSizeCallback", opGlfwSetWindowSizeCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "glfw.SetKeyCallback", opGlfwSetKeyCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)                 // TODO : to deprecate
	opcodes.RegisterFunction(prgrm, "glfw.SetMouseButtonCallback", opGlfwSetMouseButtonCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil) // TODO : to deprecate
	opcodes.RegisterFunction(prgrm, "glfw.SetCursorPosCallback", opGlfwSetCursorPosCallback, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR), nil)     // TODO : to deprecate
	opcodes.RegisterFunction(prgrm, "glfw.GetCursorPos", opGlfwGetCursorPos, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_F64, ast.ConstCxArg_F64))
	opcodes.RegisterFunction(prgrm, "glfw.SetInputMode", opGlfwSetInputMode, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "glfw.SetWindowPos", opGlfwSetWindowPos, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "glfw.GetKey", opGlfwGetKey, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "glfw.func_i32_i32", opGlfwFuncI32I32, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "glfw.call_i32_i32", opGlfwCallI32I32, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "glfw.GetWindowContentScale", opGlfwGetWindowContentScale, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "glfw.GetMonitorContentScale", opGlfwGetMonitorContentScale, nil, opcodes.Out(ast.ConstCxArg_F32, ast.ConstCxArg_F32))

	// gltext
	opcodes.RegisterFunction(prgrm, "gltext.LoadTrueType", opGltextLoadTrueType, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_STR, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gltext.LoadTrueTypeCore", opGltextLoadTrueTypeCore, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_STR, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "gltext.Printf", opGltextPrintf, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_F32, ast.ConstCxArg_F32, ast.ConstCxArg_STR), nil)
	opcodes.RegisterFunction(prgrm, "gltext.Metrics", opGltextMetrics, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gltext.Texture", opGltextTexture, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gltext.NextGlyph", opGltextNextGlyph, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_STR, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gltext.GlyphBounds", opGltextGlyphBounds, nil, opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gltext.GlyphMetrics", opGltextGlyphMetrics, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "gltext.GlyphInfo", opGltextGlyphInfo, opcodes.In(ast.ConstCxArg_STR, ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32))

	// goal
	opcodes.RegisterFunction(prgrm, "al.LoadWav", opAlLoadWav, opcodes.In(ast.ConstCxArg_STR), opcodes.Out(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_I64, ast.Slice(types.UI8)))

	// openal
	opcodes.RegisterFunction(prgrm, "al.CloseDevice", opAlCloseDevice, nil, nil)
	opcodes.RegisterFunction(prgrm, "al.DeleteBuffers", opAlDeleteBuffers, opcodes.In(ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "al.DeleteSources", opAlDeleteSources, opcodes.In(ast.Slice(types.I32)), nil)
	opcodes.RegisterFunction(prgrm, "al.DeviceError", opAlDeviceError, nil, opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "al.Error", opAlError, nil, opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "al.Extensions", opAlExtensions, nil, opcodes.Out(ast.ConstCxArg_STR))
	opcodes.RegisterFunction(prgrm, "al.OpenDevice", opAlOpenDevice, nil, nil)
	opcodes.RegisterFunction(prgrm, "al.PauseSources", opAlPauseSources, opcodes.In(ast.Slice(types.I32)), nil)
	opcodes.RegisterFunction(prgrm, "al.PlaySources", opAlPlaySources, opcodes.In(ast.Slice(types.I32)), nil)
	opcodes.RegisterFunction(prgrm, "al.Renderer", opAlRenderer, nil, opcodes.Out(ast.ConstCxArg_STR))
	opcodes.RegisterFunction(prgrm, "al.RewindSources", opAlRewindSources, opcodes.In(ast.Slice(types.I32)), nil)
	opcodes.RegisterFunction(prgrm, "al.StopSources", opAlStopSources, opcodes.In(ast.Slice(types.I32)), nil)
	opcodes.RegisterFunction(prgrm, "al.Vendor", opAlVendor, nil, opcodes.Out(ast.ConstCxArg_STR))
	opcodes.RegisterFunction(prgrm, "al.Version", opAlVersion, nil, opcodes.Out(ast.ConstCxArg_STR))
	opcodes.RegisterFunction(prgrm, "al.GenBuffers", opAlGenBuffers, opcodes.In(ast.ConstCxArg_I32), opcodes.Out(ast.Slice(types.I32)))
	opcodes.RegisterFunction(prgrm, "al.BufferData", opAlBufferData, opcodes.In(ast.ConstCxArg_I32, ast.ConstCxArg_I32, ast.ConstCxArg_UND_TYPE, ast.ConstCxArg_I32), nil)
	opcodes.RegisterFunction(prgrm, "al.GenSources", opAlGenSources, opcodes.In(ast.ConstCxArg_I32), opcodes.Out(ast.Slice(types.I32)))
	opcodes.RegisterFunction(prgrm, "al.SourceBuffersProcessed", opAlSourceBuffersProcessed, opcodes.In(ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "al.SourceBuffersQueued", opAlSourceBuffersQueued, opcodes.In(ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "al.SourceQueueBuffers", opAlSourceQueueBuffers, opcodes.In(ast.ConstCxArg_I32, ast.Slice(types.I32)), nil)
	opcodes.RegisterFunction(prgrm, "al.SourceState", opAlSourceState, opcodes.In(ast.ConstCxArg_I32), opcodes.Out(ast.ConstCxArg_I32))
	opcodes.RegisterFunction(prgrm, "al.SourceUnqueueBuffers", opAlSourceUnqueueBuffers, opcodes.In(ast.ConstCxArg_I32, ast.Slice(types.I32)), nil)
}
