package globals

var CxProgramPath string = ""

//only used one place
/*
var KeywordMap map[string]int = map[string]int{
	"func":      stage1.FUNC,
	"var":       stage1.VAR,
	"package":   stage1.PACKAGE,
	"if":        stage1.IF,
	"else":      stage1.ELSE,
	"for":       stage1.FOR,
	"struct":    stage1.STRUCT,
	"import":    stage1.IMPORT,
	"return":    stage1.RETURN,
	"goto":      stage1.GOTO,
	"new":       stage1.NEW,
	"bool":      stage1.BOOL,
	"i8":        stage1.I8,
	"ui8":       stage1.UI8,
	"i16":       stage1.I16,
	"ui16":      stage1.UI16,
	"i32":       stage1.I32,
	"ui32":      stage1.UI32,
	"f32":       stage1.F32,
	"i64":       stage1.I64,
	"ui64":      stage1.UI64,
	"f64":       stage1.F64,
	"str":       stage1.STR,
	"aff":       stage1.AFF,
	"union":     stage1.UNION,
	"enum":      stage1.ENUM,
	"const":     stage1.CONST,
	"case":      stage1.CASE,
	"default":   stage1.DEFAULT,
	"switch":    stage1.SWITCH,
	"break":     stage1.BREAK,
	"continue":  stage1.CONTINUE,
	"type":      stage1.TYPE,
	":dl":       stage1.DSTATE,
	":dLocals":  stage1.DSTATE,
	":ds":       stage1.DSTACK,
	":dStack":   stage1.DSTACK,
	":dp":       stage1.DPROGRAM,
	":dProgram": stage1.DPROGRAM,
	":package":  stage1.SPACKAGE,
	":struct":   stage1.SSTRUCT,
	":func":     stage1.SFUNC,
	":rem":      stage1.REM,
	//":step":     STEP,
	//":tStep":    TSTEP,
	//":tstep":    TSTEP,
	//":pStep":    PSTEP,
	//":pstep":    PSTEP,
	":aff":    stage1.CAFF,
	"def":     stage1.DEF,
	"clauses": stage1.CLAUSES,
	"field":   stage1.FIELD,
	"true":    stage1.BOOLEAN_LITERAL,
	"false":   stage1.BOOLEAN_LITERAL,
}
*/


