// +build base opengl

package cxcore

const (
	// os
	CONST_OS_RUN_SUCCESS = iota + 0xFFFF
	CONST_OS_RUN_EMPTY_CMD
	CONST_OS_RUN_PANIC
	CONST_OS_RUN_START_FAILED
	CONST_OS_RUN_WAIT_FAILED
	CONST_OS_RUN_TIMEOUT

	// os.FileModes (FIXME: these are uint32 in Go, with _DIR & _TYPE exceeding math.MaxInt32)
	//CONST_OS_FILEMODE_DIR
	CONST_OS_FILEMODE_APPEND
	CONST_OS_FILEMODE_EXCLUSIVE
	CONST_OS_FILEMODE_TEMPORARY
	CONST_OS_FILEMODE_SYMLINK
	CONST_OS_FILEMODE_DEVICE
	CONST_OS_FILEMODE_NAMED_PIPE
	CONST_OS_FILEMODE_SOCKET
	CONST_OS_FILEMODE_SETUID
	CONST_OS_FILEMODE_SETGID
	CONST_OS_FILEMODE_CHAR_DEVICE
	CONST_OS_FILEMODE_STICKY
	CONST_OS_FILEMODE_IRREGULAR
	//CONST_OS_FILEMODE_TYPE
	CONST_OS_FILEMODE_PERM

	// json
	CONST_JSON_TOKEN_NULL
	CONST_JSON_TOKEN_DELIM
	CONST_JSON_TOKEN_BOOL
	CONST_JSON_TOKEN_F64
	CONST_JSON_TOKEN_NUMBER
	CONST_JSON_TOKEN_STR
	CONST_JSON_DELIM_CURLY_LEFT
	CONST_JSON_DELIM_CURLY_RIGHT
	CONST_JSON_DELIM_SQUARE_LEFT
	CONST_JSON_DELIM_SQUARE_RIGHT
)

const (
	OS_RUN_SUCCESS = iota
	OS_RUN_EMPTY_CMD
	OS_RUN_PANIC // 2
	OS_RUN_START_FAILED
	OS_RUN_WAIT_FAILED
	OS_RUN_TIMEOUT
)

func init() {
	// os
	AddConstCode(CONST_OS_RUN_SUCCESS, "os.RUN_SUCCESS", TYPE_I32, FromI32(OS_RUN_SUCCESS))
	AddConstCode(CONST_OS_RUN_EMPTY_CMD, "os.RUN_EMPTY_CMD", TYPE_I32, FromI32(OS_RUN_EMPTY_CMD))
	AddConstCode(CONST_OS_RUN_PANIC, "os.RUN_PANIC", TYPE_I32, FromI32(OS_RUN_PANIC))
	AddConstCode(CONST_OS_RUN_START_FAILED, "os.RUN_START_FAILED", TYPE_I32, FromI32(OS_RUN_START_FAILED))
	AddConstCode(CONST_OS_RUN_WAIT_FAILED, "os.RUN_WAIT_FAILED", TYPE_I32, FromI32(OS_RUN_WAIT_FAILED))
	AddConstCode(CONST_OS_RUN_TIMEOUT, "os.RUN_TIMEOUT", TYPE_I32, FromI32(OS_RUN_TIMEOUT))

	// os.FileModes (FIXME: these are uint32 in Go, with _DIR & _TYPE exceeding math.MaxInt32)
	//AddConstCode( CONST_OS_FILEMODE_DIR                , "os.ModeDir"                    , TYPE_I32, FromI32(2147483648))
	AddConstCode(CONST_OS_FILEMODE_APPEND, "os.ModeAppend", TYPE_I32, FromI32(1073741824))
	AddConstCode(CONST_OS_FILEMODE_EXCLUSIVE, "os.ModeExclusive", TYPE_I32, FromI32(536870912))
	AddConstCode(CONST_OS_FILEMODE_TEMPORARY, "os.ModeTemporary", TYPE_I32, FromI32(268435456))
	AddConstCode(CONST_OS_FILEMODE_SYMLINK, "os.ModeSymlink", TYPE_I32, FromI32(134217728))
	AddConstCode(CONST_OS_FILEMODE_DEVICE, "os.ModeDevice", TYPE_I32, FromI32(67108864))
	AddConstCode(CONST_OS_FILEMODE_NAMED_PIPE, "os.ModeNamedPipe", TYPE_I32, FromI32(33554432))
	AddConstCode(CONST_OS_FILEMODE_SOCKET, "os.ModeSocket", TYPE_I32, FromI32(16777216))
	AddConstCode(CONST_OS_FILEMODE_SETUID, "os.ModeSetuid", TYPE_I32, FromI32(8388608))
	AddConstCode(CONST_OS_FILEMODE_SETGID, "os.ModeSetgid", TYPE_I32, FromI32(4194304))
	AddConstCode(CONST_OS_FILEMODE_CHAR_DEVICE, "os.ModeCharDevice", TYPE_I32, FromI32(2097152))
	AddConstCode(CONST_OS_FILEMODE_STICKY, "os.ModeSticky", TYPE_I32, FromI32(1048576))
	AddConstCode(CONST_OS_FILEMODE_IRREGULAR, "os.ModeIrregular", TYPE_I32, FromI32(524288))
	//AddConstCode( CONST_OS_FILEMODE_TYPE               , "os.ModeType"                   , TYPE_I32, FromI32(2399666176))
	AddConstCode(CONST_OS_FILEMODE_PERM, "os.ModePerm", TYPE_I32, FromI32(511))

	// json
	AddConstCode(CONST_JSON_TOKEN_NULL, "json.TOKEN_NULL", TYPE_I32, FromI32(JSON_TOKEN_NULL))
	AddConstCode(CONST_JSON_TOKEN_DELIM, "json.TOKEN_DELIM", TYPE_I32, FromI32(JSON_TOKEN_DELIM))
	AddConstCode(CONST_JSON_TOKEN_BOOL, "json.TOKEN_BOOL", TYPE_I32, FromI32(JSON_TOKEN_BOOL))
	AddConstCode(CONST_JSON_TOKEN_F64, "json.TOKEN_F64", TYPE_I32, FromI32(JSON_TOKEN_F64))
	AddConstCode(CONST_JSON_TOKEN_NUMBER, "json.TOKEN_NUMBER", TYPE_I32, FromI32(JSON_TOKEN_NUMBER))
	AddConstCode(CONST_JSON_TOKEN_STR, "json.TOKEN_STR", TYPE_I32, FromI32(JSON_TOKEN_STR))
	AddConstCode(CONST_JSON_DELIM_CURLY_LEFT, "json.DELIM_CURLY_LEFT", TYPE_I32, FromI32(JSON_DELIM_CURLY_LEFT))
	AddConstCode(CONST_JSON_DELIM_CURLY_RIGHT, "json.DELIM_CURLY_RIGHT", TYPE_I32, FromI32(JSON_DELIM_CURLY_RIGHT))
	AddConstCode(CONST_JSON_DELIM_SQUARE_LEFT, "json.DELIM_SQUARE_LEFT", TYPE_I32, FromI32(JSON_DELIM_SQUARE_LEFT))
	AddConstCode(CONST_JSON_DELIM_SQUARE_RIGHT, "json.DELIM_SQUARE_RIGHT", TYPE_I32, FromI32(JSON_DELIM_SQUARE_RIGHT))
}
